"""empty message

Revision ID: b00e9734a022
Revises: 7b2e7e9122e9
Create Date: 2020-06-30 21:58:02.477869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b00e9734a022"
down_revision = "7b2e7e9122e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
