"""first migration

Revision ID: 470a64f7a08b
Revises: 
Create Date: 2020-06-28 00:20:41.984795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470a64f7a08b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
